<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <WarningsAsErrors>nullable</WarningsAsErrors>
    <Company>T.SAIFUDDIN &amp; CO.</Company>
    <Product>TS Quotation System</Product>
    <Version>0.9.0</Version>
    <InvariantGlobalization>false</InvariantGlobalization>
  </PropertyGroup>
</Project>
