<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsTestProject>false</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Quotation.Server\Quotation.Server.csproj" />
    <ProjectReference Include="..\..\src\Quotation.ApiClient\Quotation.ApiClient.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
  </ItemGroup>
</Project>
