<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Quotation.Pdf</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Quotation.Core\Quotation.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="PDFsharp" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Fonts\*.ttf" />
    <None Include="Fonts\*.txt" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Quotation.Pdf.Tests" />
  </ItemGroup>
</Project>
